version: "3.1"

services:
  BBDD:
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: pwauser
      MYSQL_PASSWORD: pwa123
      MYSQL_DATABASE: pwa2019
    ports:
      - 4000:3306
    volumes:
      - ./mysqldata:/var/lib/mysql

  APP_Server:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
    environment:
      DDBB_NAME: pwa2019
      DDBB_HOST: BBDD
      DDBB_USER: pwauser
      DDBB_PASSWORD: pwa123
    ports:
      - 8000:80

  PHPMyAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: BBDD
      PMA_PORT: 3306
      PMA_USER: pwauser
      PMA_PASSWORD: pwa123
    ports:
      - 8001:80